#!/usr/bin/env node

const path = require("path");
const fs = require("fs");
const vite = require("vite");
const pwa_plugin = require("vite-plugin-pwa");
const colors = require("tailwindcss/colors");
const { Command } = require("commander");
const program = new Command();

const icons_main = [
    {
        src: "/logo/proto-512.v2.png",
        sizes: "512x512",
        type: "image/png",
    },
    {
        src: "/logo/proto-512-maskable.v2.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
    },
    {
        src: "/logo/proto-512-monochrome.v2.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "monochrome",
    },
];
const icons = [
    ...icons_main,
    // generated
    {
        src: "/icons/windows11/SmallTile.scale-100.png",
        sizes: "71x71",
    },
    {
        src: "/icons/windows11/SmallTile.scale-125.png",
        sizes: "89x89",
    },
    {
        src: "/icons/windows11/SmallTile.scale-150.png",
        sizes: "107x107",
    },
    {
        src: "/icons/windows11/SmallTile.scale-200.png",
        sizes: "142x142",
    },
    {
        src: "/icons/windows11/SmallTile.scale-400.png",
        sizes: "284x284",
    },
    {
        src: "/icons/windows11/Square150x150Logo.scale-100.png",
        sizes: "150x150",
    },
    {
        src: "/icons/windows11/Square150x150Logo.scale-125.png",
        sizes: "188x188",
    },
    {
        src: "/icons/windows11/Square150x150Logo.scale-150.png",
        sizes: "225x225",
    },
    {
        src: "/icons/windows11/Square150x150Logo.scale-200.png",
        sizes: "300x300",
    },
    {
        src: "/icons/windows11/Square150x150Logo.scale-400.png",
        sizes: "600x600",
    },
    {
        src: "/icons/windows11/Wide310x150Logo.scale-100.png",
        sizes: "310x150",
    },
    {
        src: "/icons/windows11/Wide310x150Logo.scale-125.png",
        sizes: "388x188",
    },
    {
        src: "/icons/windows11/Wide310x150Logo.scale-150.png",
        sizes: "465x225",
    },
    {
        src: "/icons/windows11/Wide310x150Logo.scale-200.png",
        sizes: "620x300",
    },
    {
        src: "/icons/windows11/Wide310x150Logo.scale-400.png",
        sizes: "1240x600",
    },
    {
        src: "/icons/windows11/LargeTile.scale-100.png",
        sizes: "310x310",
    },
    {
        src: "/icons/windows11/LargeTile.scale-125.png",
        sizes: "388x388",
    },
    {
        src: "/icons/windows11/LargeTile.scale-150.png",
        sizes: "465x465",
    },
    {
        src: "/icons/windows11/LargeTile.scale-200.png",
        sizes: "620x620",
    },
    {
        src: "/icons/windows11/LargeTile.scale-400.png",
        sizes: "1240x1240",
    },
    {
        src: "/icons/windows11/Square44x44Logo.scale-100.png",
        sizes: "44x44",
    },
    {
        src: "/icons/windows11/Square44x44Logo.scale-125.png",
        sizes: "55x55",
    },
    {
        src: "/icons/windows11/Square44x44Logo.scale-150.png",
        sizes: "66x66",
    },
    {
        src: "/icons/windows11/Square44x44Logo.scale-200.png",
        sizes: "88x88",
    },
    {
        src: "/icons/windows11/Square44x44Logo.scale-400.png",
        sizes: "176x176",
    },
    {
        src: "/icons/windows11/StoreLogo.scale-100.png",
        sizes: "50x50",
    },
    {
        src: "/icons/windows11/StoreLogo.scale-125.png",
        sizes: "63x63",
    },
    {
        src: "/icons/windows11/StoreLogo.scale-150.png",
        sizes: "75x75",
    },
    {
        src: "/icons/windows11/StoreLogo.scale-200.png",
        sizes: "100x100",
    },
    {
        src: "/icons/windows11/StoreLogo.scale-400.png",
        sizes: "200x200",
    },
    {
        src: "/icons/windows11/SplashScreen.scale-100.png",
        sizes: "620x300",
    },
    {
        src: "/icons/windows11/SplashScreen.scale-125.png",
        sizes: "775x375",
    },
    {
        src: "/icons/windows11/SplashScreen.scale-150.png",
        sizes: "930x450",
    },
    {
        src: "/icons/windows11/SplashScreen.scale-200.png",
        sizes: "1240x600",
    },
    {
        src: "/icons/windows11/SplashScreen.scale-400.png",
        sizes: "2480x1200",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-16.png",
        sizes: "16x16",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-20.png",
        sizes: "20x20",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-24.png",
        sizes: "24x24",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-30.png",
        sizes: "30x30",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-32.png",
        sizes: "32x32",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-36.png",
        sizes: "36x36",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-40.png",
        sizes: "40x40",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-44.png",
        sizes: "44x44",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-48.png",
        sizes: "48x48",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-60.png",
        sizes: "60x60",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-64.png",
        sizes: "64x64",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-72.png",
        sizes: "72x72",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-80.png",
        sizes: "80x80",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-96.png",
        sizes: "96x96",
    },
    {
        src: "/icons/windows11/Square44x44Logo.targetsize-256.png",
        sizes: "256x256",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-16.png",
        sizes: "16x16",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-20.png",
        sizes: "20x20",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-24.png",
        sizes: "24x24",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-30.png",
        sizes: "30x30",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-32.png",
        sizes: "32x32",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-36.png",
        sizes: "36x36",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-40.png",
        sizes: "40x40",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-44.png",
        sizes: "44x44",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-48.png",
        sizes: "48x48",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-60.png",
        sizes: "60x60",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-64.png",
        sizes: "64x64",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-72.png",
        sizes: "72x72",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-80.png",
        sizes: "80x80",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-96.png",
        sizes: "96x96",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-unplated_targetsize-256.png",
        sizes: "256x256",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-16.png",
        sizes: "16x16",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-20.png",
        sizes: "20x20",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-24.png",
        sizes: "24x24",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-30.png",
        sizes: "30x30",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-32.png",
        sizes: "32x32",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-36.png",
        sizes: "36x36",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-40.png",
        sizes: "40x40",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-44.png",
        sizes: "44x44",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-48.png",
        sizes: "48x48",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-60.png",
        sizes: "60x60",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-64.png",
        sizes: "64x64",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-72.png",
        sizes: "72x72",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-80.png",
        sizes: "80x80",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-96.png",
        sizes: "96x96",
    },
    {
        src: "/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-256.png",
        sizes: "256x256",
    },
    {
        src: "/icons/android/android-launchericon-512-512.png",
        sizes: "512x512",
    },
    {
        src: "/icons/android/android-launchericon-192-192.png",
        sizes: "192x192",
    },
    {
        src: "/icons/android/android-launchericon-144-144.png",
        sizes: "144x144",
    },
    {
        src: "/icons/android/android-launchericon-96-96.png",
        sizes: "96x96",
    },
    {
        src: "/icons/android/android-launchericon-72-72.png",
        sizes: "72x72",
    },
    {
        src: "/icons/android/android-launchericon-48-48.png",
        sizes: "48x48",
    },
    {
        src: "/icons/ios/16.png",
        sizes: "16x16",
    },
    {
        src: "/icons/ios/20.png",
        sizes: "20x20",
    },
    {
        src: "/icons/ios/29.png",
        sizes: "29x29",
    },
    {
        src: "/icons/ios/32.png",
        sizes: "32x32",
    },
    {
        src: "/icons/ios/40.png",
        sizes: "40x40",
    },
    {
        src: "/icons/ios/50.png",
        sizes: "50x50",
    },
    {
        src: "/icons/ios/57.png",
        sizes: "57x57",
    },
    {
        src: "/icons/ios/58.png",
        sizes: "58x58",
    },
    {
        src: "/icons/ios/60.png",
        sizes: "60x60",
    },
    {
        src: "/icons/ios/64.png",
        sizes: "64x64",
    },
    {
        src: "/icons/ios/72.png",
        sizes: "72x72",
    },
    {
        src: "/icons/ios/76.png",
        sizes: "76x76",
    },
    {
        src: "/icons/ios/80.png",
        sizes: "80x80",
    },
    {
        src: "/icons/ios/87.png",
        sizes: "87x87",
    },
    {
        src: "/icons/ios/100.png",
        sizes: "100x100",
    },
    {
        src: "/icons/ios/114.png",
        sizes: "114x114",
    },
    {
        src: "/icons/ios/120.png",
        sizes: "120x120",
    },
    {
        src: "/icons/ios/128.png",
        sizes: "128x128",
    },
    {
        src: "/icons/ios/144.png",
        sizes: "144x144",
    },
    {
        src: "/icons/ios/152.png",
        sizes: "152x152",
    },
    {
        src: "/icons/ios/167.png",
        sizes: "167x167",
    },
    {
        src: "/icons/ios/180.png",
        sizes: "180x180",
    },
    {
        src: "/icons/ios/192.png",
        sizes: "192x192",
    },
    {
        src: "/icons/ios/256.png",
        sizes: "256x256",
    },
    {
        src: "/icons/ios/512.png",
        sizes: "512x512",
    },
    {
        src: "/icons/ios/1024.png",
        sizes: "1024x1024",
    },
];
const manifest = {
    administrator: {
        id: "1",
        name: "School Monitoring Administrator",
        short_name: "School Monitoring Administrator",
        description: "Web Monitoring School for Administrator",
        start_url: "/administrator/dashboard",
        scope: "/administrator/",
        display: "standalone",
        display_override: ["window-controls-overlay"],
        orientation: "any",
        launch_handler: {
            client_mode: "navigate-existing",
        },
        theme_color: colors.blue[500],
        background_color: colors.blue[500],
        related_applications: [],
        prefer_related_applications: false,
        shortcuts: [
            {
                name: "Dashboard",
                short_name: " Dashboard",
                url: "/administrator/dashboard",
                description: "Dashboard Page",
                icons: icons_main,
            },
            {
                name: "School Information",
                short_name: "School Information",
                url: "/administrator/data_master/school_information/list",
                description: "School Information",
                icons: icons_main,
            },
            {
                name: "List of Employee",
                short_name: "List of Employee",
                url: "/administrator/users/employee/list",
                description: "List of Employee",
                icons: icons_main,
            },
            {
                name: "List of Student",
                short_name: "List of Student",
                url: "/administrator/users/student/list",
                description: "List of Student",
                icons: icons_main,
            },
        ],
        icons,
    },
    student: {
        id: "1",
        name: "School Monitoring Student",
        short_name: "School Monitoring Student",
        description: "Web Monitoring School for Student",
        start_url: "/student/dashboard",
        scope: "/student/",
        display: "standalone",
        display_override: ["window-controls-overlay"],
        orientation: "any",
        launch_handler: {
            client_mode: "navigate-existing",
        },
        theme_color: colors.blue[500],
        background_color: colors.blue[500],
        related_applications: [],
        prefer_related_applications: false,
        shortcuts: [
            {
                name: "Student Dashboard",
                short_name: "Student Dashboard",
                url: "/student/dashboard",
                description: "Student Dashboard Page",
                icons: icons_main,
            },
        ],
        icons,
    },
};

program.name("node").description("CLI to node utilities").version("0.1.0");
program
    .command("pwa")
    .description("PWA utils")
    .action(() => {
        console.log("pwa utils");
    });
program
    .command("pwa:build")
    .description("PWA build")
    .option("-n, --name [string]", "name of manifest")
    .action(async (options) => {
        let keys = Object.keys(manifest);
        if (options.name && keys.includes(options.name)) {
            keys = [options.name];
        }
        for (const key of keys) {
            console.log("build", key);
            await vite.build({
                build: {
                    outDir: `public/${key}`,
                },
                plugins: [
                    pwa_plugin.VitePWA({
                        registerType: "prompt",
                        injectRegister: "auto",
                        strategies: "injectManifest",
                        base: `/${key}/`,
                        srcDir: `resources/js/components/${key}`,
                        filename: "sw.js",
                        injectManifest: {
                            additionalManifestEntries: [
                                // { revision: "2", url: `/${key}/dashboard` },
                                {
                                    revision: "1",
                                    url: `/${key}/offline`,
                                },
                            ],
                        },
                        includeAssets: [
                            "favicon.ico",
                            "apple-touch-icon.png",
                            "masked-icon.svg",
                        ],
                        manifestFilename: "site.webmanifest",
                        manifest: manifest[key],
                    }),
                ],
            });
        }
    });
// program
//     .command("pwa:move")
//     .description("PWA move compiled file")
//     .action(() => {
//         const src = "public/build";
//         const dest = "public";
//         const files_to_move = ["site.webmanifest", "sw.js"];
//         for (const file of files_to_move) {
//             fs.copyFile(path.join(src, file), path.join(dest, file), (err) => {
//                 console.log(
//                     path.join(src, file),
//                     "->",
//                     path.join(dest, file),
//                     err ? "fail" : "success"
//                 );
//                 err && console.error(err);
//             });
//         }
//     });
program
    .command("pwa:remove")
    .description("PWA remove compiled file")
    .option("-n, --name [string]", "name of manifest")
    .action(async (options) => {
        let dirs = Object.keys(manifest);
        if (options.name && dirs.includes(options.name)) {
            dirs = [options.name];
        }
        const src = "public";
        for (const dir of dirs) {
            fs.rm(path.join(src, dir), { recursive: true }, (err) => {
                console.log(path.join(src, dir), err ? "fail" : "success");
                err && console.error(err);
            });
        }
    });

program.parse();
